In [24]:
import pandas as pd
import pyarrow.parquet as pq
import numpy as np

In [21]:
bios=pd.read_csv("./data/bios.csv")
# print(bios.loc[(bios["height_cm"] >= 220) & (bios['born_country']=='USA')])
display(bios.loc[
    bios["name"].str.contains("",case=False, na=False)
])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [ ]:
#filtering data using query functions
bios.query("born_country=='USA'")

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [37]:
coffee=pd.read_csv('./warmup-data/coffee.csv')
coffee['price']=2.99
mask = (coffee["Coffee Type"] == "Espresso") & (coffee["Day"] == "Monday")
coffee['new_price']=np.where(mask ,7.99,2.99)
coffee = coffee.drop(columns=["price"])
display(coffee)

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       7.99
1      Monday       Latte          15       2.99
2     Tuesday    Espresso          30       2.99
3     Tuesday       Latte          20       2.99
4   Wednesday    Espresso          35       2.99
5   Wednesday       Latte          25       2.99
6    Thursday    Espresso          40       2.99
7    Thursday       Latte          30       2.99
8      Friday    Espresso          45       2.99
9      Friday       Latte          35       2.99
10   Saturday    Espresso          45       2.99
11   Saturday       Latte          35       2.99
12     Sunday    Espresso          45       2.99
13     Sunday       Latte          35       2.99